### ISSUE TITLE
JUnit5 snippets

### ISSUE THREAD

**Issue by georgejdli** [wesleyegberto/vscode-java-tests#1]
Any plans to support JUnit5 for generated snippets?

**Comment by wesleyegberto** [comment]
Sure.
I'm still creating some snippets from cases I've encountered, like:

```java
@Test
@ParameterizedTest(name = "{0} plus {1} should be {2}")
@CsvSource({
	"0, 0, 0",
	"1, 0, 1",
	"1, 1, 2",
})
public void shouldAddTwoNumbers(int x, int y, int expectedSum) {
}
```

Feel free to open a PR with snippets that you would like to see or comment an example so I can put there.

Cheers

**Comment by wesleyegberto** [comment]
I've published a version to support JUnit 5.
Any problems or suggestions will be welcome.
