### ISSUE TITLE
Plans to support JUnit5 Jupiter imports

### ISSUE THREAD

**Issue by bkbonner** [wesleyegberto/vscode-java-tests#2]
Thank you, I really like the plugin, but I'd really like it to support JUnit 5 (JUnit4 is no longer supported as of SpringBoot 2.4).

It looks like the default imports in:  https://github.com/wesleyegberto/vscode-java-tests/blob/master/src/file-content-generator.ts aren't for JUnit 5.   As well as the imports in java.json default to Junit 4 setup.   @RunsWith is also no longer available.   

![image](https://user-images.githubusercontent.com/667769/109737279-c296be00-7b93-11eb-9638-6072f398bea2.png)

Do you have plans to support for Jupiter?   either with a setting to specify the Junit Version?   Or a separate version for Jupiter?

**Comment by wesleyegberto** [comment]
Glad you like, hope it is make you work more productive.

I'm currently working on support JUnit 5 by adding correct imports and test structure. Also will add some new forms of test.

By now, I will provide a way to configure for which version the code will be generated (4, 5 or always ask which one), at least until I figure out how to resolve the version in the POM.xml.

**Comment by rafaelcoelho** [comment]
Hi @wesleyegberto any news upon that? This plugin is very useful and the code snipping is amazing the only thing is to generate the snipped only based on Junit4.

**Comment by wesleyegberto** [comment]
I've published a version to support JUnit 5.
Any problems or suggestions will be welcome.
