### ISSUE TITLE
Upload plugin to open-vsx.org

### ISSUE THREAD

**Issue by ebramirez** [wesleyegberto/vscode-java-tests#8]
Hi,

All non-microsoft versions of VSCode use an alternative plugin repository located in www.open-vsx.org. It would be amazing if you could push your plugin to that repo with new releases, maybe using [this action](https://github.com/marketplace/actions/publish-vs-code-extension).

Thanks for your hard work.

**Comment by wesleyegberto** [comment]
Hi

Great, thank you for the link, made it easy.
I already created an account and I will check on the weekend how to create the namespace to push it.

**Comment by wesleyegberto** [comment]
Hi

Just published to Open VSX.
Could you download it to see if everything is ok?

https://www.open-vsx.org/extension/wesleyegberto/vscode-java-tests

**Comment by ebramirez** [comment]
Hi Wesley,

Yes, I could install it perfectly. Thanks a lot for this!
